version: '3.1'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./.local/mongodb-data:/data/db

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    command: server /data
    volumes:
      - ./.local/minio-data:/data
#  identity-db:
#    image: postgres:latest
#    restart: always
#    volumes:
#      - .personal/tests-db/data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: "data"
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "0"
#    ports:
#      - "5433:5432"
#  tests-db:
#    image: postgres:15.2
#    restart: always
#    volumes:
#      - ./.local/tests-db/data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: "data"
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "0"
#    ports:
#      - "5432:5432"
#  tests-service:
#    image: tests-service
#    restart: always
#    ports:
#      - "7080:8080"
#    command:
#      - "java"
#      - "-jar"
#      - "-Dparams.postgres.host=tests-db"
#      - "app.jar"
#  neo4j:
#    image: neo4j:latest
#    restart: always
#    volumes:
#      - ~/rutt/requirements/data:/data
#      - ~/rutt/requirements/logs:/logs
#      - ~/rutt/requirements/import:/var/lib/neo4j/import
#      - ~/rutt/requirements/plugins:/plugins
#    environment:
#      - NEO4J_AUTH=neo4j/0
#    ports:
#      - "7474:7474"
#      - "7687:7687"
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "2080:8080"
