server:
  servlet:
    context-path: /tests/api
  port: 8080
spring:
  datasource:
    username: postgres
    password: 0
    url: jdbc:postgresql://${params.postgres.host}:${params.postgres.port}/data
  jpa:
    hibernate:
      ddl-auto: update

params:
  postgres:
    host: localhost
    port: 5432
