server:
  port: 8081

aws:
  accessKeyId: minio
  secretKey: password
  s3:
    endpoint: http://localhost:9000

spring:
  data:
    mongodb:
      uri: mongodb://mongo:password@localhost:27017/files
