server:
  servlet:
    context-path: /files/api
  port: 8081

aws:
  accessKeyId: minio
  secretKey: password
  s3:
    endpoint: http://localhost:9000

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/yourdbname
