name: Test service
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Compile
        working-directory: ./tests-service
        run: mvn --batch-mode compile
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Test
        working-directory: ./tests-service
        run: mvn --batch-mode verify

      - name: Publish JaCoCo report
          uses: codecov/codecov-action@v2
          with:
            file: target/site/jacoco/jacoco.xml
